import {
  Users, Heart, Music, BookOpen, Baby, HandHelping,
  Shield, Soup, Church, Camera
} from "lucide-react";

export const allMinistries = [
  {
    slug: "womens-fellowship",
    icon: Heart,
    title: "Women's Fellowship",
    description: "Building strong relationships among women through prayer, study, and mutual support.",
    fullDescription: "The Women's Fellowship is a vibrant community where women are encouraged to grow spiritually, support one another, and serve the church with love and dedication. Through weekly Bible studies, prayer circles, and outreach events, we foster deep and lasting bonds rooted in faith.",
    meetingTime: "Every Saturday at 9:00 AM",
    leader: "Sister Mary Asante",
    activities: ["Weekly Bible Study", "Prayer Circles", "Community Outreach", "Annual Retreat"],
    heroImage: ["/women3.jpg", { position: "top" }],
    images: [
        { src: "/womenf1.jpg", caption: "Women's Fellowship meeting" },
        { src: "/womenf2.jpg", caption: "Women's Fellowship activity" },
        { src: "/womenf.jpg", caption: "Women's Fellowship event" },
        { src: "/womenf4.jpg", caption: "Women's Fellowship gathering" }
    ]
  },
  {
    slug: "mens-ministry",
    icon: Shield,
    title: "Men's Fellowship",
    description: "Equipping men to be godly leaders in their homes, church, and community.",
    fullDescription: "The Men's Fellowship is dedicated to raising men of integrity and faith. We equip men to lead with courage in their families, workplaces, and communities through discipleship, mentorship, and accountability groups.",
    meetingTime: "Every Saturday at 8:00 AM",
    leader: "Elder Kofi Mensah",
    activities: ["Discipleship Groups", "Mentorship Program", "Community Service", "Leadership Workshops"],
  },
  {
    slug: "prayer-ministry",
    icon: Church,
    title: "Nahatheen | Prayer Group",
    description: "Establishing prayer warriors committed to interceding for our church and community.",
    fullDescription: "Nahatheen is our dedicated prayer ministry, raising up intercessors who stand in the gap for the church, the nation, and the world. We believe in the transforming power of prayer and commit ourselves to consistent, fervent intercession.",
    meetingTime: "Tuesdays & Thursdays at 6:00 AM",
    leader: "Pastor Emmanuel Boateng",
    activities: ["Early Morning Prayer", "Night Vigils", "Intercessory Sessions", "Fasting & Prayer Weeks"],
  },
  {
    slug: "seenim-ministry",
    icon: HandHelping,
    title: "SEENIM",
    description: "A ministry focused on nurturing students and young believers through fellowship, discipleship, and spiritual growth.",
    fullDescription: "SEENIM is our student and young believer ministry, creating a safe and vibrant space for young people to discover their faith. Through discipleship, fellowship, and practical service, we help the next generation build a solid foundation in Christ.",
    meetingTime: "Fridays at 5:00 PM",
    leader: "Bro. Daniel Owusu",
    activities: ["Bible Study Groups", "Campus Outreach", "Discipleship Classes", "Social Events"],
  },
  {
    slug: "faith-society-ministry",
    icon: BookOpen,
    title: "Faith-Society",
    description: "A ministry focused on strengthening believers in their faith through prayer, Bible study, and spiritual guidance.",
    fullDescription: "Faith-Society is a fellowship of believers committed to deepening their walk with God. Through systematic Bible study, prayer, and mutual accountability, we help members grow in faith and apply God's Word to everyday life.",
    meetingTime: "Wednesdays at 6:30 PM",
    leader: "Sis. Abena Frimpong",
    activities: ["Systematic Bible Study", "Prayer Meetings", "Spiritual Retreats", "Testimony Sharing"],
     heroImage: ["/faith1.jpg", { position: "top" }],
    images: [
        { src: "/faith.jpg", caption: "Women's Fellowship meeting" },
        { src: "/faith2.jpg", caption: "Women's Fellowship activity" },
        { src: "/faith3.webp", caption: "Women's Fellowship event" },
        { src: "/choir4.jpg", caption: "Women's Fellowship gathering" }
    ]
  },
  {
    slug: "worship-ministry",
    icon: Music,
    title: "Worship Ministry",
    description: "Leading our congregation in spirit-filled worship through music and praise.",
    fullDescription: "The Worship Ministry is the heartbeat of our Sunday services and special events. Our team of musicians, singers, and worship leaders are dedicated to creating an atmosphere where God is glorified and hearts are opened to His presence.",
    meetingTime: "Rehearsals: Saturdays at 3:00 PM",
    leader: "Min. Grace Acheampong",
    activities: ["Sunday Worship Leading", "Special Event Performances", "Worship Workshops", "Instrument Training"],
  },
  {
    slug: "youth-ministry",
    icon: Users,
    title: "Youth Ministry",
    description: "Empowering the next generation through vibrant study, fellowship, and community service.",
    fullDescription: "Our Youth Ministry is a dynamic community where teenagers and young adults are challenged to live boldly for Christ. Through engaging programs, leadership development, and community service, we equip youth to make an impact in their schools and neighborhoods.",
    meetingTime: "Sundays at 2:00 PM",
    leader: "Youth Pastor Ama Darko",
    activities: ["Youth Services", "Leadership Training", "Community Projects", "Sports & Recreation"],
  },
  {
    slug: "childrens-ministry",
    icon: Baby,
    title: "Children's Ministry",
    description: "Nurturing young hearts and minds with age-appropriate biblical teachings.",
    fullDescription: "The Children's Ministry is a fun and safe environment where kids aged 3–12 learn about God through stories, songs, crafts, and games. We partner with parents to raise children who love God and treat others with kindness.",
    meetingTime: "Sundays during main service",
    leader: "Sis. Portia Agyemang",
    activities: ["Sunday School", "Bible Stories & Crafts", "Vacation Bible School", "Children's Choir"],
  },
  {
    slug: "choir-ministry",
    icon: Music,
    title: "Choir Ministry",
    description: "A team of dedicated singers and musicians who lead the congregation in worship through music.",
    fullDescription: "The Choir Ministry uses the gift of music to glorify God and minister to the congregation. Our choir participates in Sunday services, special celebrations, and outreach events, always striving for excellence in worship.",
    meetingTime: "Rehearsals: Fridays at 6:00 PM",
    leader: "Choirmaster Samuel Tetteh",
    activities: ["Sunday Choir Performance", "Special Concerts", "Outreach Events", "Vocal Training"],
     heroImage: ["/choir.jpg", { position: "top" }],
    images: [
        { src: "/choir1.jpg", caption: "Choir rehearsal" },
        { src: "/choir2.jpg", caption: "Choir performance" },
        { src: "/choir3.jpg", caption: "Choir event" },
        { src: "/choir4.jpg", caption: "Choir gathering" }
    ]
  },
  {
    slug: "media-ministry",
    icon: Camera,
    title: "Media Ministry",
    description: "Managing church media, live streaming, and digital communication.",
    fullDescription: "The Media Ministry ensures that our church's message reaches beyond the four walls of our building. From live streaming services to managing our social media presence and producing visual content, our team uses technology to advance the Gospel.",
    meetingTime: "Active every Sunday & special events",
    leader: "Bro. Nana Oti",
    activities: ["Live Streaming", "Photography & Videography", "Social Media Management", "Graphic Design"],
  },
  {
    slug: "welfare-ministry",
    icon: Soup,
    title: "Welfare Ministry",
    description: "Supporting members and community through benevolence and care programs.",
    fullDescription: "The Welfare Ministry is the hands and feet of Jesus in our community. We identify needs within our congregation and the surrounding community and respond with practical support — from food assistance to hospital visits and bereavement support.",
    meetingTime: "Monthly meetings — first Monday at 5:00 PM",
    leader: "Deaconess Rose Amoah",
    activities: ["Food Assistance", "Hospital & Home Visitation", "Bereavement Support", "Emergency Aid"],
  },
  {
    slug: "community-outreach",
    icon: HandHelping,
    title: "Community Outreach",
    description: "Serving our local community through various outreach campaigns and initiatives.",
    fullDescription: "The Community Outreach Ministry is passionate about sharing God's love beyond the church walls. Through evangelism campaigns, community clean-ups, health fairs, and school programs, we actively serve and transform our neighborhoods.",
    meetingTime: "Monthly outreach — last Saturday",
    leader: "Evang. Philip Nkrumah",
    activities: ["Evangelism Campaigns", "Community Clean-Ups", "Health Fairs", "School Outreach Programs"],
  },
];